#pragma kernel CSMain

struct Cell
{
    int3 position;
    int pressure;
};

int4 bounds;
float4 globalWind;
int2 gasPerSolid;

Texture2D<float> solid;
Texture2D<float> gas;

RWStructuredBuffer<Cell> cells;


[numthreads(10,1,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
   Cell cell = cells[id.x];
   int2 uvGas = cell.position;
   int2 uvSolid = cell.position/gasPerSolid;
   cell.pressure = gas[cell.position.xy] ;
   
   cells[id.x] = cell;
}
